### ISSUE TITLE
Fail to build from source code on Ubuntu 18.04

### ISSUE THREAD

**Issue by lmsreborn** [vesoft-inc/nebula#1244]
**Describe the bug(__must be provided__)**
Follow the instructions in `Build source code` doc , but fail to build on Ubuntu 18.04

**Your Environments(__must be provided__)**
  * OS: `uname -a` Ubuntu 18.04
  * Compliler: `g++ --version` or `clang++ --version` 7.4.0
  * CPU: `lscpu` Intel(R) Core(TM) i7-9750H

**How To Reproduce(__must be provided__)**
Just follow the instructions in https://github.com/vesoft-inc/nebula/blob/master/docs/manual-EN/3.build-develop-and-administration/1.build/1.build-source-code.md#build-source-code

**Expected behavior**
Build from source code successfully.

**Additional context**

when linking with libkrb5.a :
```
/opt/nebula/third-party/bin/ld: /opt/nebula/third-party/lib/libkrb5.a(dnsglue.o): in function `krb5int_dns_init':
dnsglue.c:(.text+0xb8): undefined reference to `__res_nsearch'
/opt/nebula/third-party/bin/ld: dnsglue.c:(.text+0xf8): undefined reference to `ns_initparse'
/opt/nebula/third-party/bin/ld: /opt/nebula/third-party/lib/libkrb5.a(dnsglue.o): in function `krb5int_dns_nextans':
dnsglue.c:(.text+0x1b5): undefined reference to `ns_parserr'
/opt/nebula/third-party/bin/ld: /opt/nebula/third-party/lib/libkrb5.a(dnsglue.o): in function `krb5int_dns_expand':
dnsglue.c:(.text+0x25c): undefined reference to `ns_name_uncompress'
collect2: error: ld returned 1 exit status

```

**Comment by lmsreborn** [comment]
My fault, set wrong cmake path. Please close this issue.

**Comment by whitewum** [comment]
Thanks for your trail. Contact us if you have any further problems.
